### ISSUE TITLE
oppo手机拍照后卡住

### ISSUE THREAD

**Issue by oudengding** [Shouheng88/iCamera#10]
使用oppo A5拍照成功后卡住了，看报错信息有：
2020-08-06 14:17:24.048 11699-12139/com.yuanli.mvplocatingcamera E/TeaLog: U SHALL NOT PASS!
    java.lang.NullPointerException: Attempt to get length of null array
        at com.bytedance.embedapplog.d.g.i(SourceFile:141)
        at com.bytedance.embedapplog.d.b.a(SourceFile:587)
        at com.bytedance.embedapplog.d.b.a(SourceFile:534)
        at com.bytedance.embedapplog.a.j.d(SourceFile:98)
        at com.bytedance.embedapplog.a.g.d(SourceFile:23)
        at com.bytedance.embedapplog.a.c.h(SourceFile:55)
        at com.bytedance.embedapplog.a.e.handleMessage(SourceFile:170)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:198)
        at android.os.HandlerThread.run(HandlerThread.java:65)

**Comment by Shouheng88** [comment]
收到

**Comment by Shouheng88** [comment]
这个确实啥也看不出……你拉最新的代码，跑一下试试，最近部分细节有调整

**Comment by Shouheng88** [comment]
试一下新的版本
