### ISSUE TITLE
打开相机后报错 Didn't find class "kotlin.jdk7.AutoCloseableKt"

### ISSUE THREAD

**Issue by TYUpya** [Shouheng88/iCamera#26]
调用打开相机后，onCameraOpened回调参数是0，然后从库内部报错
机型 Xiaomi MI CC 9e，UI系统 MIUI12.0.4，AndroidOS 10，使用库版本 me.shouheng.icamera:icamera:0.1.5-beta

异常信息如下：
`2021-05-23 21:59:00.177  E/AndroidRuntime: FATAL EXCEPTION: BaseCameraManager
    Process: com.xxx.demo, PID: 10480
    java.lang.NoClassDefFoundError: Failed resolution of: Lkotlin/jdk7/AutoCloseableKt;
        at me.shouheng.icamera.manager.impl.Camera2Manager$onPreviewImageAvailableListener$1.onImageAvailable(Camera2Manager.kt:122)
        at android.media.ImageReader$ListenerHandler.handleMessage(ImageReader.java:798)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:225)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "kotlin.jdk7.AutoCloseableKt" on path: DexPathList[[zip file "/data/app/com.xxx.demo-goXzqrLyLHdkJ--DzFoMXg==/base.apk"],nativeLibraryDirectories=[/data/app/com.xxx.demo-goXzqrLyLHdkJ--DzFoMXg==/lib/arm64, /system/lib64, /system/product/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:230)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at me.shouheng.icamera.manager.impl.Camera2Manager$onPreviewImageAvailableListener$1.onImageAvailable(Camera2Manager.kt:122) 
        at android.media.ImageReader$ListenerHandler.handleMessage(ImageReader.java:798) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:225) 
        at android.os.HandlerThread.run(HandlerThread.java:67) `

**Comment by TYUpya** [comment]
2021-05-23 21:59:00.177  E/AndroidRuntime: FATAL EXCEPTION: BaseCameraManager
    Process: com.xxx.demo, PID: 10480
    java.lang.NoClassDefFoundError: Failed resolution of: Lkotlin/jdk7/AutoCloseableKt;
        at me.shouheng.icamera.manager.impl.Camera2Manager$onPreviewImageAvailableListener$1.onImageAvailable(Camera2Manager.kt:122)
        at android.media.ImageReader$ListenerHandler.handleMessage(ImageReader.java:798)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:225)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "kotlin.jdk7.AutoCloseableKt" on path: DexPathList[[zip file "/data/app/com.xxx.demo-goXzqrLyLHdkJ--DzFoMXg==/base.apk"],nativeLibraryDirectories=[/data/app/com.xxx.demo-goXzqrLyLHdkJ--DzFoMXg==/lib/arm64, /system/lib64, /system/product/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:230)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at me.shouheng.icamera.manager.impl.Camera2Manager$onPreviewImageAvailableListener$1.onImageAvailable(Camera2Manager.kt:122) 
        at android.media.ImageReader$ListenerHandler.handleMessage(ImageReader.java:798) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:225) 
        at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by Shouheng88** [comment]
你有改动 gradle 版本吗，我之前用的是 kotlin-stdlib-jdk7 系列的 kotlin，从报错信息上面看应该是缺少了这个类

**Comment by TYUpya** [comment]
我暂时没用 kotlin 开发，能不能整个 Java 版？
